### ISSUE TITLE
Qusetion about pokec

### ISSUE THREAD

**Issue by ntuwork** [LUOyk1999/tunedGNN#5]
-

**Comment by LUOyk1999** [comment]
Hello! Could you please tell me what version of python you are using and what is your GPU?

**Comment by ntuwork** [comment]
> Hello! Could you please tell me what version of Python you are using and what is your GPU model?

Thanks for reply! py==3.9.20, I have tried 3 types of GPU: 4090, 3090 ,and A6000.

**Comment by LUOyk1999** [comment]
> > Hello! Could you please tell me what version of Python you are using and what is your GPU model?
> 
> Thanks for reply! py==3.9.20, I have tried 3 types of GPU: 4090, 3090 ,and A6000.

Great! I also encountered this issue with python 3.9 before. Try using python 3.7:

`Tested with Python 3.7, PyTorch 1.12.1, and PyTorch Geometric 2.3.1, dgl 1.0.2.`

**Comment by ntuwork** [comment]
> > > Hello! Could you please tell me what version of Python you are using and what is your GPU model?
> > 
> > 
> > Thanks for reply! py==3.9.20, I have tried 3 types of GPU: 4090, 3090 ,and A6000.
> 
> Great! I also encountered this issue with python 3.9 before. Try using python 3.7:
> 
> `Tested with Python 3.7, PyTorch 1.12.1, and PyTorch Geometric 2.3.1, dgl 1.0.2.`

Thanks, I'm trying to configure it. Can you please provide some reasons why changing the python version solves the problem?

**Comment by LUOyk1999** [comment]
Oh. All the code runs on python 3.7, which is mentioned in the project's README document. I am now investigating the cause of this.

**Comment by ntuwork** [comment]
> Oh. All the code runs on python 3.7, which is mentioned in the project's README document. I am now investigating the cause of this.

Ok, thanks!
